### PR TITLE
Fixes spaces in project name

### LINKED ISSUE #150: spaces in repo name gives error
### Description: 

Not sure whats the best way to handle this...And we are kind of already hinting user to use (dashes instead of space in example name) 

Screenshot 2024-11-06 at 12 12 59 PM

### PR DESCRIPTION
**Pull request by rin-st**
An error appears [here](https://github.com/scaffold-eth/create-eth/blob/7e323702c60a602a3377ba9aec174d0b6e424284/src/tasks/create-first-git-commit.ts#L16) only when used foundry with project name with spaces at the end. It throws because ` /` (space + `/`) is interpreted as separation between arguments. All other variants " a", "a b" etc works as expected

So idea is to restrict space usage at the end of the project name and allow all others

I added a check when prompting for a name: you can't go the next steps until you have no spaces/tabs at the end of the project name. Also added project field reset for adventurers who will try to deceive cli and try to use something like `yarn cli "space-at-the-end "`

https://github.com/user-attachments/assets/72474d25-bfd1-4f3f-bb79-4f514e6cf490

how it looks with the extension
image

Fixes #150

### CODE REVIEW

File: src/utils/parse-arguments-into-options.ts [hunk 1]
```diff
@@ -101,6 +101,11 @@ export async function parseArgumentsIntoOptions(
     );
   }
 
+  if (project && /\s$/.test(project)) {
+    project = null;
+    console.log(chalk.yellow(" Project name cannot end with whitespace. Enter a valid project name."));
```
Comment (technophile-04) [inline src/utils/parse-arguments-into-options.ts:106]: I think we can remove this? Since this is not shown to the user right?  

Also maybe just add a comment about regex saying it checks for any tralling spaces in end? 

or maybe move that regex to some declarative var so that we can use it in   `prompt-for-missing-options` too?

Comment (rin-st) [reply src/utils/parse-arguments-into-options.ts:107]: > I think we can remove this? Since this is not shown to the user right?

It's shown to the user, see yellow text in the video (from 0:02) and also screenshot

> or maybe move that regex to some declarative var so that we can use it in prompt-for-missing-options too?

Thanks!  [f99426a](https://github.com/scaffold-eth/create-eth/pull/176/commits/f99426a0c50e88cecdeccd465e5d2c312c32687e)

Comment (technophile-04) [reply src/utils/parse-arguments-into-options.ts:107]: Ohhh yess sorry my bad! So it's shown when you pass the directory name directly while initiating the cli

**Review by technophile-04 — APPROVED** [review]
Thanks @rin-st really nice!! and works great!  And happy to merge as it 🙌

Was just researching on DX from other create CLI's  

1. Regarding project path, I liked how create-next-app is validating the path. 
     - checkout this [line](https://github.com/vercel/next.js/blob/35acd7e1faae66feddeffe6362fae9fb5a5b1281/packages/create-next-app/index.ts#L162) 
     - and this their [validate function](https://github.com/vercel/next.js/blob/35acd7e1faae66feddeffe6362fae9fb5a5b1281/packages/create-next-app/helpers/validate-pkg.ts#L13) 

2. Initially I thought maybe we should ourselves trim leading and inital space (being forgiving) but looking at other CLI they don't do it and show Invalid project path like us now 🙌  so need to change anything. 

On point 1 should we use that? Maybe it's a bit overpowered but worth it and more robust / future proof. Saying this because maybe in future user entering some weird path might break CLI (can be caused if use some other lib in create-eth cli is not able to parse or maybe some foundry changes) 

Also its shows warning on specific stuff whats wrong: 

<details>

<summary>
Space errror : 
</summary>

Screenshot 2024-12-30 at 11 29 05 AM


</details> 

<details>

<summary>
Weird char which might cause issue
</summary>

Screenshot 2024-12-30 at 11 29 53 AM


</details>

**Comment by rin-st** [comment]
Thanks Shiv!

I copied their [validate](https://github.com/scaffold-eth/create-eth/pull/176/commits/bb077658f2dda2f0a7f94d820cea5e1ccb1a661b#diff-7bb91118b5b44d6bcc855e07238b86f4f9f83fdad99ac9d21b4367f7521a3bdc) function so now cli shows all the errors at the start. But when prompting it shows only one error (same as in [create-next-app](https://github.com/vercel/next.js/blob/35acd7e1faae66feddeffe6362fae9fb5a5b1281/packages/create-next-app/index.ts#L166)) since if we want to show all it requires to add workarounds and I think it's not worth it.

How it works now:

https://github.com/user-attachments/assets/379d50c5-1ac0-4a49-8bb0-75d53b48647c

File: src/utils/parse-arguments-into-options.ts [hunk 2]
```diff
@@ -74,7 +75,7 @@ export async function parseArgumentsIntoOptions(
       "-h": "--help",
     },
     {
-      argv: rawArgs.slice(2).map(a => a.toLowerCase()),
+      argv: rawArgs.slice(2),
```
Comment (rin-st) [inline src/utils/parse-arguments-into-options.ts:78]: also, I removed lowerCasing here since uppercase letters are deprecated (see video) and it's not clear to user that name will be lowercased

Comment (technophile-04) [reply src/utils/parse-arguments-into-options.ts:78]: Noice yup!!

**Comment by technophile-04** [comment]
> But when prompting it shows only one error (same as in [create-next-app](https://github.com/vercel/next.js/blob/35acd7e1faae66feddeffe6362fae9fb5a5b1281/packages/create-next-app/index.ts#L166)) since if we want to show all it requires to add workarounds and I think it's not worth it.

Yup yup not worth it and the current version feels nice too so no required!

Thanks @rin-st!! Merging this 🙌
