### PR TITLE
Fix: lint instances action should fail when install is unsuccessful

### LINKED ISSUE #341: Lint instances action doesn't exit on install error
See https://github.com/scaffold-eth/create-eth/actions/runs/17327524542/job/49195310403, cancelled manually

<details><summary>Details</summary>
<p>

Image

Image

</p>
</details>

### PR DESCRIPTION
**Pull request by rin-st**
Fixes #341 

See how it works in penult commit action https://github.com/scaffold-eth/create-eth/actions/runs/17402303106/job/49398011892

That commit was for testing purposes and last commit removed wrong param [7246ce0](https://github.com/scaffold-eth/create-eth/pull/342/commits/7246ce04985bb0eb2541fe5f97483536862465f1), so actions are successful

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -73,5 +73,6 @@ export async function createProject(options: Options) {
   } catch (error) {
     console.log("%s Error occurred", chalk.red.bold("ERROR"), error);
     console.log("%s Exiting...", chalk.red.bold("Uh oh! 😕 Sorry about that!"));
+    throw error;
```
Comment (technophile-04) [inline src/main.ts:76]: Ohh since here we are throwing the error forward just throw it forward without logging it, and in `cli.ts` we move this lines? 

```ts
 console.log("%s Error occurred", chalk.red.bold("ERROR"), error);
console.log("%s Exiting...", chalk.red.bold("Uh oh! 😕 Sorry about that!"));
``` 

Because I feel `Uh oh! 😕 Sorry about that! Exiting...` should come very last 

Currently if error occurs in one of `tasks` of `main.ts` we get: 

Image

Comment (rin-st) [reply src/main.ts]: Thanks! Moved logs from `main.ts` to `cli.ts` and removed try catch in `main.ts` since we don't need it anymore

image

**Review by technophile-04 — APPROVED** [review]
Thanks Rinat!!
