### PR TITLE
fix: providers

### LINKED ISSUE #301: [Beta] After switching theme full components tree remounts
It causes refetching all api's, show all loaders etc

Reason: when we use [composeProviders](https://github.com/scaffold-eth/create-eth/blob/5cb178acb562272d8799d5fc586aee183252775f/templates/base/packages/nextjs/components/ScaffoldEthAppWithProviders.tsx.template.mjs#L73) function, all the Providers are recreated and hence all the tree below. We need not only find a way to memoize providers, but just change the prop when it changed, not recreate the provider with new prop. Or just use JSX

To test: 
- Create instance from beta
- Add this to home or debug (you'll see the loaders here) page
```
  useEffect(() => {
    console.log("mounted");
  }, []);
```
- switch theme and check console. You'll see "mounted" on every theme switch

Found by Pablo here (theme switcher part) https://github.com/scaffold-eth/se-2-challenges/pull/305#pullrequestreview-2982299318

### PR DESCRIPTION
**Pull request by rin-st**
See details of the current providers problems in the issue. #301 

I removed `ComposedProvider` component and according utils, since it caused recreating of the full components tree when changing any prop of any provider, or even when just rerender of `ScaffoldEthAppWithProviders`.

I changed it to direct JSX generation, so we have all the providers again,  something like this
```
    <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        <RainbowKitProvider
          avatar={BlockieAvatar}
          theme={mounted ? (isDarkMode ? darkTheme() : lightTheme()) : lightTheme()}
        >
          <ProgressBar height="3px" color="#2299dd" />
          <ScaffoldEthApp>{children}</ScaffoldEthApp>
        </RainbowKitProvider>
      </QueryClientProvider>
    </WagmiProvider>
```
And when changing props everything works as expected. 
Arguments of the template are same as before

To test remounting:
- add this log to `/app/page.tsx` in the instance
```
  useEffect(() => {
    console.log("mounted");
  }, []);
```
- and then switch theme. Remount doesn't happen. No logs in console after mount. (If you switch page you'll see log when returning to the homepage but it's expected)

To test duplicating wallets on rainbowkit modal:
- switch between home and debug pages by clicking to header menu buttons
- disconnect, click to connect. Rainbowkit modal opened. You shouldn't see any duplicated wallets

--- 

PR with previous providers change: https://github.com/scaffold-eth/create-eth/pull/278

---

note:
What I also tried before this solution: 
- memoize providers/values/move objects out of react component so always the same objects are used
- use some external libs
nothing worked

Fixes #301

### CODE REVIEW

File: templates/base/packages/nextjs/components/ScaffoldEthAppWithProviders.tsx.template.mjs [hunk 1]
```diff
@@ -15,9 +15,21 @@ const contents = ({ preContent, globalClassNames, extraProviders, overrideProvid
...
+    const openingIndentation = index === 0 ? '' : '    ' + '  '.repeat(index);
+    return `${openingIndentation}<${providerName} ${propAssignments}>`;
+  }).join('\n');
+
+  const contentIndentation = '  '.repeat(providerEntries.length);
+
+  const providerClosingTags = providerEntries.reverse().map(([providerName], index) => {
+    const closingIndentation = (index === 0 ? '' : '    ') + '  '.repeat(providerEntries.length - index - 1);
+    return `${closingIndentation}</${providerName}>`;
+  }).join('\n');
```
Comment (technophile-04) [inline templates/base/packages/nextjs/components/ScaffoldEthAppWithProviders.tsx.template.mjs:32]: Can we remove the indentation logic? Since anywhich ways it will be formatted by prettier so lets remove that logic : 

```ts
  const providerEntries = Object.entries(providersObject);
  const providerOpeningTags = providerEntries.map(([providerName, props]) => {
    const propAssignments = Object.entries(props).map(([propName, propValue]) => 
      `${propName}={${stringify(propValue)}}`
    ).join(' ');
    return `<${providerName} ${propAssignments}>`;
  }).join('\n');

  const providerClosingTags = providerEntries.reverse().map(([providerName]) => {
    return `</${providerName}>`;
  }).join('\n');

```

File: templates/base/packages/nextjs/components/ScaffoldEthAppWithProviders.tsx.template.mjs [hunk 2]
```diff
@@ -68,15 +79,11 @@ export const ScaffoldEthAppWithProviders = ({ children }: { children: React.Reac
...
-  const ComposedProviders = composeProviders(providers);
-
   return (
-    <ComposedProviders>
-      <ProgressBar height="3px" color="#2299dd" />
-      <ScaffoldEthApp>{children}</ScaffoldEthApp>
-    </ComposedProviders>
+    ${providerOpeningTags}
+    ${contentIndentation}<ProgressBar height="3px" color="#2299dd" />
+    ${contentIndentation}<ScaffoldEthApp>{children}</ScaffoldEthApp>
```
Comment (technophile-04) [inline templates/base/packages/nextjs/components/ScaffoldEthAppWithProviders.tsx.template.mjs:85]: From here we remove the `contentIndentation` too if we plan to with https://github.com/scaffold-eth/create-eth/pull/302/files#r2186577321 

```tsx
    ${providerOpeningTags}
    <ProgressBar height="3px" color="#2299dd" />
    <ScaffoldEthApp>{children}</ScaffoldEthApp>
    ${providerClosingTags}
```

**Review by technophile-04 — COMMENTED** [review]
Tyms @rin-st 🙏! This is amazing and nice!! Just added a comment regarding removing of the indentation logic so that its more easy to read 🙌 

Tested it out and works great!!

File: templates/base/packages/nextjs/components/ScaffoldEthAppWithProviders.tsx.template.mjs (hunk 2 above)
Comment (rin-st) [reply templates/base/packages/nextjs/components/ScaffoldEthAppWithProviders.tsx.template.mjs]: Thanks!

With suggested code (both comments) and `--skip` flag, resulting code looks like that:
```
return (
    <WagmiProvider config={wagmiConfig}>
<QueryClientProvider client={queryClient}>
<RainbowKitProvider avatar={BlockieAvatar} theme={mounted ? (isDarkMode ? darkTheme() : lightTheme()) : lightTheme()}>
    <ProgressBar height="3px" color="#2299dd" />
    <ScaffoldEthApp>{children}</ScaffoldEthApp>
    </RainbowKitProvider>
</QueryClientProvider>
</WagmiProvider>
  );
```

I removed indentation logic but added two chages [778698c](https://github.com/scaffold-eth/create-eth/pull/302/commits/778698cf51f4bcfb4752febc5e778988f7c9d420):
1. join with spaces `.join('\n    ')`
2. indentation of content in return
```
return (
    ${providerOpeningTags}
      <ProgressBar height="3px" color="#2299dd" />
      <ScaffoldEthApp>{children}</ScaffoldEthApp>
    ${providerClosingTags}
  );
```

So result at least looks readable
```
return (
    <WagmiProvider config={wagmiConfig}>
    <QueryClientProvider client={queryClient}>
    <RainbowKitProvider avatar={BlockieAvatar} theme={mounted ? (isDarkMode ? darkTheme() : lightTheme()) : lightTheme()}>
      <ProgressBar height="3px" color="#2299dd" />
      <ScaffoldEthApp>{children}</ScaffoldEthApp>
    </RainbowKitProvider>
    </QueryClientProvider>
    </WagmiProvider>
  );
```

**Review by technophile-04 — APPROVED** [review]
Tysm Rinat!! Working great!
