### PR TITLE
Typecheck for arguments

### LINKED ISSUE #191: Add typecheck for passing arguments
Context: https://github.com/scaffold-eth/create-eth/pull/184#issuecomment-2563564738

> Maybe for better DX we can also add args typecheck like

> If (type of default argument !== type of passed argument) then throw an error "hey, wrong argument type here, see default param and example extension"

> so we could be inconsistent sometimes when we need too, e.g. in this .env.example case and devs will figure it out explicitly and earlier

The [rules](https://github.com/scaffold-eth/create-eth/issues/190) should be set before starting to work on this

### PR DESCRIPTION
**Pull request by rin-st**
Adds typecheck for passed arguments. Fixed default args which had wrong types

tested with extension https://github.com/scaffold-eth/create-eth-extensions/tree/beta-extra-examples 

```
yarn cli -e https://github.com/scaffold-eth/create-eth-extensions/tree/beta-extra-examples
```

Fixes #191

### CODE REVIEW

File: templates/utils.js [hunk 1]
```diff
@@ -43,11 +43,19 @@ export const withDefaults =
...
             .map(name => `\`${name}\``)
             .join(", ")}`,
         );
       }
+
+      if (typeof receivedArgs[receivedArgName][0] !== typeof expectedArgsDefaults[receivedArgName]) {
+        throw new Error(
+          `Template argument \`${receivedArgName}\` has wrong type. Expecting ${
+            typeof expectedArgsDefaults[receivedArgName]
+          }. Received ${typeof receivedArgs[receivedArgName][0]}.`,
```
Comment (technophile-04) [inline templates/utils.js:56]: If the array was received it says object. 

image


This what cursor suggested and I like: 

image

**Review by technophile-04 — COMMENTED** [review]
Thanks Rinat really nice! I think this is what we need 🙌 

Question is there a simple way we can also log the file name in which the wrong arg was received? Becuase currently it just logs the variable name. 

image

File: templates/utils.js (hunk 1 above)
Comment (rin-st) [reply templates/utils.js]: Thanks! Added it [4476c17](https://github.com/scaffold-eth/create-eth/pull/270/commits/4476c17b239abd349482cf1028f55cffa5ebde21)

And changed default value of manifest `extraContents` to object [f896823](https://github.com/scaffold-eth/create-eth/pull/270/commits/f896823036099d508936de85c7ad9efc9aa2c1e7)

**Review by technophile-04 — APPROVED** [review]
> Tried to play with it but for now didn't find a way except passing that name as param to withDefaults. I think maybe let's fix it in different PR? I can create an issue

Ohh yeah didn't find any straight forward way too :(...Yup let's merge this and tinker in different PR 🙌 Also I think this is something we can add after launching beta too
