### PR TITLE
Fix: name as path when initializing 

### LINKED ISSUE #207: Allow project name as path while initializing the CLI
## Description: 

Currently we allow path through wizard but it would be great if we can allow passing the path directly to CLI 

https://github.com/user-attachments/assets/0ad671c4-0356-4a26-8df6-3fe1d6e3c41b

### PR DESCRIPTION
**Pull request by rin-st**
added `basename(resolve(...))` as [here](https://github.com/scaffold-eth/create-eth/blob/main/src/utils/prompt-for-missing-options.ts#L29) so validation works only for the last folder in path

fixes #207

### CODE REVIEW

File: src/utils/validate-name.ts [hunk 1]
```diff
@@ -10,7 +11,7 @@ type ValidateNpmNameResult =
     };
 
 export function validateNpmName(name: string): ValidateNpmNameResult {
-  const nameValidation = validateProjectName(name);
+  const nameValidation = validateProjectName(basename(resolve(name)));
```
Comment (technophile-04) [inline src/utils/validate-name.ts:14]: So then let's remove `basename(resolve(name))` from here?  https://github.com/scaffold-eth/create-eth/blob/main/src/utils/prompt-for-missing-options.ts#L29

**Comment by technophile-04** [comment]
Nice catch thanks rinat! just added a small comment

File: src/utils/validate-name.ts (hunk 1 above)
Comment (rin-st) [reply src/utils/validate-name.ts:14]: good point, thanks! Removed [81696ba](https://github.com/scaffold-eth/create-eth/pull/208/commits/81696baba8105d6e2a032e7ba8ebefcf97687432)

**Review by technophile-04 — APPROVED** [review]
Thanks Rinat! Works great!
