### PR TITLE
Fixes github rate limit

### LINKED ISSUE #260: Github rate limit
### Description: 

We are making 3 github calls. 

1. Check if extension exist using the github link (https://github.com/...) [here](https://github.com/scaffold-eth/create-eth/blob/24b731927189403420c10ec1c1c085cb4f0ef148/src/utils/external-extensions.ts#L70)
2. Clonning the extension [here](https://github.com/scaffold-eth/create-eth/blob/24b731927189403420c10ec1c1c085cb4f0ef148/src/tasks/copy-template-files.ts#L325)
3. Making and API request to check for solidity frameworks given by extension [here](https://github.com/scaffold-eth/create-eth/blob/24b731927189403420c10ec1c1c085cb4f0ef148/src/utils/external-extensions.ts#L168)
   - here we use api.github.com 
   - the reason we make this request is to show solidity framework option on CLI 
      - if both hardhat and foundry are provided by extension we show both 
      - if any one is present we allow user select any one. 

I think we get github rate limit only because of 3 since gh API limit 5k req per hour (but we can check if 1 or 2 are also causing most likely not the case) 

### Some solutions: 

Carlos suggested about have "silent error" 

> silent error = if we get an error (maybe only for 429) we just ignore it (with a warning, maybe)...and move on. And they might get another error later, but at least it's not a faltal error on start. 

Just extending it ahead, if we get rate limited in CLI interface we show user all three options (hardhat, foundry, none) it's fine if extension doesn't provide foundry we have default foundry and extension should at least work (this is how CLI used work earlier). Maybe we show a small warning or something that this happened and check on gh to select solidity framework which is only given by extension or something. 

I think let's have this fallback even if we have gh proxy (tracked in #213)

### PR DESCRIPTION
**Pull request by rin-st**
Everything is already described inside #260, I just wrote the code. Thanks for suggestions!

Instead of calling github API I used two calls to github.com using Promise.all

Test examples:
with both solidity frameworks, options will be hardhat and foundry
```
yarn cli --skip -e erc-20
```

with one solidity framework (hh), no options and autoinstall
```
yarn cli --skip -e challenge-0-simple-nft
```

with no solidity framework, options are hardhat, foundry and none
```
yarn cli --skip -e subgraph
```

Fixes #260

### CODE REVIEW

**Review by technophile-04 — APPROVED** [review]
Tysm @rin-st!! I think this is great! 

Just extending your main comment: 

If the github request fails, we show the all three options to user (hardhat, foundry, none) which is good! 


Just cc @carletex shall we log some warning or we just let it fail silently? I think failing silently is fine? I mean now with github.com its very unlikely to fail so it's fine if we don't log the warning or anything?

**Comment by carletex** [comment]
> Just cc @carletex shall we log some warning or we just let it fail silently? I think failing silently is fine? I mean now with github.com its very unlikely to fail so it's fine if we don't log the warning or anything?

I think a warning won't hurt, but no big deal for me, so up to y'all

**Comment by rin-st** [comment]
Added warning

From initial issue message:
> Just extending it ahead, if we get rate limited in CLI interface we show user all three options (hardhat, foundry, none) it's fine if extension doesn't provide foundry we have default foundry and extension should at least work (this is how CLI used work earlier). Maybe we show a small warning or something that this happened and check on gh to select solidity framework which is only given by extension or something.

So also added possibility to choose the framework if framework check fails

File: src/utils/external-extensions.ts [hunk 1]
```diff
@@ -165,13 +165,27 @@ export const getSolidityFrameworkDirsFromExternalExtension = async (
...
-  return filterSolidityFrameworkDirs(directories);
+  const frameworkChecks = solidityFrameworks.map(async framework => {
+    const githubUrl = `https://github.com/${ownerName}/${repoName}/tree/${branch}/extension/packages/${framework}`;
+    try {
+      const res = await fetch(githubUrl);
+      if (res.ok) {
+        return framework as SolidityFramework;
+      }
+      // Directory doesn't exist
+      return null;
```
Comment (technophile-04) [inline src/utils/external-extensions.ts:177]: I think we should be deterministic here. 

```ts
If (res.status === 200) return framework as SolidityFramework;

// Actually directory not found
if(res.status === 404) return null;

// Any status code other than that we should show console warning. This can rate limit code (429 or 403) or any other code
throw new error (`${framework.charAt(0).toUpperCase() + framework.slice(1)} framework check failed with status `${res.status}`. You can verify it at ${githubUrl}.`)
```

And in catch we could just show message console.warn(error.message) and then return framework 

what do you think? 

Saying this because currently if we get rate limiting we want log the warning. 

--- 

Here are github API status codes: 

Screenshot 2025-05-23 at 3 05 59 PM
Screenshot 2025-05-23 at 3 06 15 PM

this are for api.github.com but shall be similar not found and rate limiting status code will be same mostly.

Comment (rin-st) [reply src/utils/external-extensions.ts]: Agree, thank you! [ea79140](https://github.com/scaffold-eth/create-eth/pull/264/commits/ea79140dfaa79756c6c1cdd96385e5426007cab7)

**Comment by technophile-04** [comment]
Tysm @rin-st works great!1
